name: reto1_donut_app_angel_avila
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.0  # Última versión de google_sign_in
  flutter_facebook_auth: ^5.0.0  # Última versión de flutter_facebook_auth
  font_awesome_flutter: ^10.3.0  # Última versión (es para el icono de googleeee)


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets: 
  - lib/icons/
  - lib/images/
